### ISSUE TITLE
Add Back To Top Button

### ISSUE THREAD

**Issue by AlpriElse** [ReflectionsProjections/rp2019#12]
Make a "Back to Top" Button Visible when past About Section

**Comment by AlpriElse** [comment]
[Something that might help](https://codyhouse.co/gem/back-to-top/)

**Comment by mrswagbhinav** [comment]
Can I take care of this? I got it working but if I make it so the button only appears after scrolling down the screen then I get a "window is not defined" sometimes. 

Should I just make a pull request with the version of the button that's always persistent but doesn't crash?

**Comment by AlpriElse** [comment]
Please make a PR with a button that appears after scrolling down past the About Section. 

With respect to the "window is not defined" issue, make sure you're not accessing window when in a component is in the /pages directory because those are rendered server-side using NextJS, so there is no window defined.

I'm not sure how you're implementing it but consider using componentDidMount(), so that code doesn't execute server-side.

**Comment by AlpriElse** [comment]
Site layout has been replanned. No longer needed.
