### ISSUE TITLE
Properly size sponsor logos.

### ISSUE THREAD

**Issue by AlpriElse** [ReflectionsProjections/rp2019#39]
We need to properly size Two Sigma on all platforms.

<img width="438" alt="Screen Shot 2019-08-25 at 6 37 12 PM" src="https://user-images.githubusercontent.com/7798116/63656819-66193e00-c767-11e9-9291-802958184dd5.png">
<img width="1026" alt="Screen Shot 2019-08-25 at 6 37 22 PM" src="https://user-images.githubusercontent.com/7798116/63656820-66193e00-c767-11e9-8984-e05dac7fd86e.png">

**Comment by PianoBin** [comment]
cannot replicate on mobile

**Comment by AlpriElse** [comment]
I think adding more sponsors might've "fixed" it.
