### ISSUE TITLE
Add links to sponsor logos.

### ISSUE THREAD

**Issue by AlpriElse** [ReflectionsProjections/rp2019#41]
We want to be able to go to the company's main website/careers page/application page when clicking the specific logo.

May need collaboration with the Corporate team.

![Aug-25-2019 18-48-02](https://user-images.githubusercontent.com/7798116/63656929-f0ae6d00-c768-11e9-960c-dcda1ba4e39e.gif)
<img width="624" alt="Screen Shot 2019-08-25 at 6 47 40 PM" src="https://user-images.githubusercontent.com/7798116/63656930-f0ae6d00-c768-11e9-8426-8134f5968c92.png">

**Comment by PradyumnaShome** [comment]
Closing via #49.
